yml modifié

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -39,39 +39,39 @@ jobs:
       run: echo "ECS_TASK_DEFINITION=${{ secrets.ECS_TASK_DEFINITION }}"
 
     - name: Update ECS Task Definition
-  run: |
-    # Obtenir la définition de tâche actuelle
-    TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION }}) || { echo "Failed to get task definition"; exit 1; }
+      run: |
+        # Obtenir la définition de tâche actuelle
+        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION }}) || { echo "Failed to get task definition"; exit 1; }
 
-    # Vérification de la famille
-    FAMILY=$(echo "$TASK_DEFINITION" | jq -r '.taskDefinition.family')
-    if [ -z "$FAMILY" ]; then
-      echo "Family is missing in task definition"; exit 1;
-    fi
+        # Vérification de la famille
+        FAMILY=$(echo "$TASK_DEFINITION" | jq -r '.taskDefinition.family')
+        if [ -z "$FAMILY" ]; then
+          echo "Family is missing in task definition"; exit 1;
+        fi
 
-    # Créer la nouvelle définition de tâche avec l'image mise à jour
-    NEW_TASK_DEFINITION=$(echo "$TASK_DEFINITION" | jq --arg IMAGE "${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG" '
-      .taskDefinition.containerDefinitions[0].image = $IMAGE |
-      del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
-      {
-        family: .taskDefinition.family, 
-        containerDefinitions: .taskDefinition.containerDefinitions, 
-        taskRoleArn: .taskDefinition.taskRoleArn, 
-        executionRoleArn: .taskDefinition.executionRoleArn, 
-        networkMode: .taskDefinition.networkMode, 
-        cpu: .taskDefinition.cpu, 
-        memory: .taskDefinition.memory, 
-        requiresCompatibilities: .taskDefinition.requiresCompatibilities, 
-        tags: [{"key": "app-version", "value": "$IMAGE_TAG"}]  # Tag dynamique avec la version de l'image
-      }
-    ')
+        # Créer la nouvelle définition de tâche avec l'image mise à jour
+        NEW_TASK_DEFINITION=$(echo "$TASK_DEFINITION" | jq --arg IMAGE "${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG" '
+          .taskDefinition.containerDefinitions[0].image = $IMAGE |
+          del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
+          {
+            family: .taskDefinition.family, 
+            containerDefinitions: .taskDefinition.containerDefinitions, 
+            taskRoleArn: .taskDefinition.taskRoleArn, 
+            executionRoleArn: .taskDefinition.executionRoleArn, 
+            networkMode: .taskDefinition.networkMode, 
+            cpu: .taskDefinition.cpu, 
+            memory: .taskDefinition.memory, 
+            requiresCompatibilities: .taskDefinition.requiresCompatibilities, 
+            tags: [{"key": "app-version", "value": "$IMAGE_TAG"}]  # Tag dynamique avec la version de l'image
+          }
+        ')
 
-    # Enregistrer la nouvelle définition de tâche
-    NEW_TASK_REVISION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION" | jq -r '.taskDefinition.taskDefinitionArn')
+        # Enregistrer la nouvelle définition de tâche
+        NEW_TASK_REVISION=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION" | jq -r '.taskDefinition.taskDefinitionArn')
 
-    # Mettre à jour le service ECS avec la nouvelle tâche
-    aws ecs update-service \
-      --cluster ${{ secrets.ECS_CLUSTER }} \
-      --service ${{ secrets.ECS_SERVICE }} \
-      --task-definition "$NEW_TASK_REVISION" \
-      --force-new-deployment
+        # Mettre à jour le service ECS avec la nouvelle tâche
+        aws ecs update-service \
+          --cluster ${{ secrets.ECS_CLUSTER }} \
+          --service ${{ secrets.ECS_SERVICE }} \
+          --task-definition "$NEW_TASK_REVISION" \
+          --force-new-deployment
